version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: snapcore-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=SnapCore

volumes:
  mongodb_data: